---
title: "mock_alpha_estimates"
author: "Kimberly Ledger"
date: "2024-09-10"
output: html_document
---

load libraries
```{r}
library(tidyverse)
library(data.table)
library(gridExtra)
library(ggsci)
```

# Read in the posteriors for mock communities
```{r}
load("/home/kimberly.ledger/nearshore_eDNA/outputs/samples_w_mocks_updated/mock_quant/mock_20241126_in1_out2.Rdata")
in1_out2 <- Output
load("/home/kimberly.ledger/nearshore_eDNA/outputs/samples_w_mocks_updated/mock_quant/mock_20241126_in1_out3.Rdata")
in1_out3 <- Output
load("/home/kimberly.ledger/nearshore_eDNA/outputs/samples_w_mocks_updated/mock_quant/mock_20241126_in1_out6.Rdata")
in1_out6 <- Output
```


## Pull out estimates of alpha, convert to CLR 
```{r}
p_space_in1_out2 <- (exp(in1_out2$pars$alpha) / rowSums(exp(in1_out2$pars$alpha))) %>% as.data.frame()
p_space_in1_out3 <- (exp(in1_out3$pars$alpha) / rowSums(exp(in1_out3$pars$alpha))) %>% as.data.frame()
p_space_in1_out6 <- (exp(in1_out6$pars$alpha) / rowSums(exp(in1_out6$pars$alpha))) %>% as.data.frame()

clr_alpha_list_in1_out2 <- compositions::clr(p_space_in1_out2)
clr_alpha_list_in1_out3 <- compositions::clr(p_space_in1_out3)
clr_alpha_list_in1_out6 <- compositions::clr(p_space_in1_out6)

clr_alpha_in1_out2 <- clr_alpha_list_in1_out2 %>% as.data.frame() 
clr_alpha_in1_out3 <- clr_alpha_list_in1_out3 %>% as.data.frame()
clr_alpha_in1_out6 <- clr_alpha_list_in1_out6 %>% as.data.frame()

colnames(clr_alpha_in1_out2) <- in1_out2$Species
colnames(clr_alpha_in1_out3) <- in1_out3$Species
colnames(clr_alpha_in1_out6) <- in1_out6$Species

clr_alpha_sum_1 <- clr_alpha_in1_out2 %>% 
                    pivot_longer( .,
                          cols = colnames(clr_alpha_in1_out2),
                          names_to="species",values_to="val") %>%
                    group_by(species) %>%
                    summarize(Mean = mean(val),
                        SD=sd(val),
                        q.025 = quantile(val,probs=0.025),
                        q.05 = quantile(val,probs=0.05),
                        q.25 = quantile(val,probs=0.25),
                        q.75 = quantile(val,probs=0.75),
                        q.95 = quantile(val,probs=0.95),
                        q.975 = quantile(val,probs=0.975)) %>% 
  mutate(calibration = "in1_out2")  

clr_alpha_sum_2 <- clr_alpha_in1_out3 %>% 
                    pivot_longer( .,
                          cols = colnames(clr_alpha_in1_out3),
                          names_to="species",values_to="val") %>%
                    group_by(species) %>%
                    summarize(Mean = mean(val),
                        SD=sd(val),
                        q.025 = quantile(val,probs=0.025),
                        q.05 = quantile(val,probs=0.05),
                        q.25 = quantile(val,probs=0.25),
                        q.75 = quantile(val,probs=0.75),
                        q.95 = quantile(val,probs=0.95),
                        q.975 = quantile(val,probs=0.975)) %>% 
  mutate(calibration = "in1_out3")

clr_alpha_sum_3 <- clr_alpha_in1_out6 %>% 
                    pivot_longer( .,
                          cols = colnames(clr_alpha_in1_out6),
                          names_to="species",values_to="val") %>%
                    group_by(species) %>%
                    summarize(Mean = mean(val),
                        SD=sd(val),
                        q.025 = quantile(val,probs=0.025),
                        q.05 = quantile(val,probs=0.05),
                        q.25 = quantile(val,probs=0.25),
                        q.75 = quantile(val,probs=0.75),
                        q.95 = quantile(val,probs=0.95),
                        q.975 = quantile(val,probs=0.975)) %>% 
  mutate(calibration = "in1_out6")

clr_alpha_all <- clr_alpha_sum_1 %>%
  bind_rows(clr_alpha_sum_2) %>%
  bind_rows(clr_alpha_sum_3) %>%
  arrange(Mean)


# get rid of reference species denotion
clr_alpha_all <- clr_alpha_all %>%
                      mutate(SP= ifelse(grepl("zRefSpecies_",species),
                                       substr(species,13,nchar(species)),
                                       as.character(species)))

p_clr <-  ggplot(clr_alpha_all) +
    geom_errorbarh(aes(xmin=q.25,xmax=q.75,y=SP),size=2,height=0) +
    geom_errorbarh(aes(xmin=q.025,xmax=q.975,y=SP),size=0.8,height=0) +
    #geom_point(aes(x=Mean,y=SP,fill=SP),size=3,shape=21) +
    geom_point(aes(x=Mean,y=SP,fill=calibration),size=3,shape=21) +
    geom_vline(xintercept=0,linetype="dashed") +
    #scale_fill_manual(values=clr_alpha_sum$manual.col %>% as.character()) +
    scale_x_continuous("Amplification Efficiency (CLR)") +
    scale_y_discrete(NULL) +
    theme_bw() +
    theme(legend.position = "right",
          axis.text.y = element_text(size=10))

p_clr
```


```{r}
#ggsave(p_clr, filename = "/home/kimberly.ledger/nearshore_eDNA/outputs/samples_w_mocks_updated/figures/clr.png", width = 8, height = 5, units = "in")
```
