---
title: "compare clr"
author: "Kimberly Ledger"
date: "2023-10-10"
output: html_document
---

compare the clr alpha (amplification efficiencies) calculated from each mock community 


libraries
```{r}
library(tidyverse)
library(ggplot2)
```

read in the data
```{r}
c1 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com1.csv")
c2 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com2.csv")
c3 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com3.csv")
c4 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com4.csv")    ### candidate to not include b/c it's the only mock community that has chinook and sockyeye, and all the salmon together in one seems to drive extreme (outlier?) estimates of alpha for the other species 
c5 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com5.csv")
c6 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com6.csv")
c7 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com7.csv")
c8 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com8.csv")
c9 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com9.csv")
c10 <- read.csv("~/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/com10.csv")


all_mock <- c1 %>%
  bind_rows(c2, c3, c4, c5, c6, c7, c8, c9, c10)

mock_w_hexa <- c1 %>%
  bind_rows(c3, c5, c6, c7, c8, c9, c10)

#my_order_communities <- c("even", "north1", "north2", "middle", "south1", "south2")
#all_mock$mock <- factor(all_mock$mock, levels = my_order_communities)

#create offset for plotting 
# all_mock <- all_mock %>%
#   mutate(offset.plot = 0,
#          offset.plot = ifelse(mock=="even",0.25,offset.plot),
#          offset.plot = ifelse(mock=="north1",0.15,offset.plot), 
#          offset.plot = ifelse(mock=="north2",0.05,offset.plot),
#          offset.plot = ifelse(mock=="middle",-0.05,offset.plot), 
#          offset.plot = ifelse(mock=="south1",-0.15,offset.plot),
#          offset.plot = ifelse(mock=="south2",-0.25,offset.plot))

#create spp index 
all_mock <- all_mock %>%
  mutate(spp.index = as.numeric(as.factor(all_mock$SP)))

#mock_w_hexa <- mock_w_hexa %>%
#  mutate(spp.index = as.numeric(as.factor(all_mock$SP)))
```


```{r, fig.width = 10}
p_clr_mock_compare <-  ggplot(mock_w_hexa) +
    geom_errorbarh(aes(xmin=q.25,xmax=q.75,y=SP),size=2,height=0) +
    geom_errorbarh(aes(xmin=q.025,xmax=q.975,y=SP),size=0.8,height=0) +
    geom_point(aes(x=Mean,y=SP,fill=mock),size=3,shape=21) +
    geom_vline(xintercept=0,linetype="dashed") +
    #scale_fill_manual(values=clr_alpha_sum$manual.col %>% as.character()) +
    scale_x_continuous("Amplification Efficiency (CLR)") +
    scale_y_discrete(NULL) +
    theme_bw() +
    theme(legend.position = "right",
          axis.text.y = element_text(size=10))

p_clr_mock_compare
```

```{r}
#ggsave(p_clr_mock_compare, filename = "/home/kimberly.ledger/nearshore_eDNA/outputs/samples_w_mock/mock_quant/clr/all.pdf", width = 10, height = 6, units = "in")
```
