---
title: "checking taxa for mock communities"
author: "Kimberly Ledger"
date: "2024-02-22"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#set working directory 
knitr::opts_knit$set(root.dir = "~/nearshore_eDNA/")
```


load libraries    
```{r}
library(tidyverse)
```


read in list of candidate species for mock communities 
```{r}
candidates <- read.csv("mock_community/candidate_spp_list.csv")
#candidates <- data.frame(taxid = "44932")
```

read in reference database - for now i'm using the outputs for the 12s expanded mifish db (https://zenodo.org/records/8409202)
```{r}
single <- read.csv("reference_db/Sequences_with_single_taxonomic_path.csv")
multiple <- read.csv("reference_db/Sequences_with_multiple_taxonomic_paths.csv")
```

filter single path taxa
```{r}
single_cand <- single %>%
  filter(taxid %in% candidates$taxid)
```

reformat and filter multiple path taxa
```{r}
my_taxid <- as.character(candidates$taxid)

multiple_expand_taxid <- multiple %>%
  separate_rows(taxid, sep = ",") %>%
  mutate(taxid = sub("^ ", "", taxid))

multiple_cand <- multiple_expand_taxid %>%
  filter(taxid %in% candidates$taxid)
```

merge and export to file that i can put into geneious 
```{r}
candidate_tax_db <- single_cand %>%
  bind_rows(multiple_cand) %>%
  arrange(species)

#write.csv(candidate_tax_db, "mock_community/candidate_spp_db.csv")
```



